### ISSUE TITLE
license is not friendly 

### ISSUE THREAD

**Issue by laopeng2021** [galliaproject/gallia-core#1]
Hello. Gallia is a great open source software.
But found that the license is not friendly, can you change it to the apache license?

Because if the license is more friendly, more people should adopt it, which is good for Gallia's future. If few people use it, Gallia is of little value.

Personal thoughts, immature, thank you.

**Comment by anthony-cros** [comment]
Hi Andy, thanks for taking the time to look at Gallia and share some feedback!

Regarding the license, did you get a chance to look at [this document](https://github.com/galliaproject/gallia-docs/blob/master/bsl.md#2-what-is-the-intent-captured-in-gallias-version-of-bsl)? This is the best way I can formulate the rationale behind the choice of the license.

**Comment by anthony-cros** [comment]
Switched to [Apache 2](https://github.com/galliaproject/gallia-core/blob/v0.5.0/LICENSE) for release [v0.5.0](https://github.com/galliaproject/gallia-core/releases/tag/v0.5.0)
